// See https://aka.ms/new-console-template for more information
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine(" --HERO-- ");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("I am so high, I can hear heaven");
Console.WriteLine();
Console.WriteLine("I am so high, I can hear heaven");
Console.WriteLine();
Console.WriteLine("Whoa, but heaven,no, heaven don't hear me");
Console.WriteLine();
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("And they say");
Console.WriteLine();
Console.WriteLine("That a hero could save us");
Console.WriteLine();
Console.WriteLine("I'm not gonna stand here and wait");
Console.WriteLine();
Console.WriteLine("I'll hold on to the wings of the eagles");
Console.WriteLine();
Console.WriteLine("Watch as we all fly away");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("Someone told me");
Console.WriteLine();
Console.WriteLine("Love would all save us");
Console.WriteLine();
Console.WriteLine("But, how can that be");
Console.WriteLine();
Console.WriteLine("Look what love gave us");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("A world full of killing");
Console.WriteLine();
Console.WriteLine("And blood spilling");
Console.WriteLine();
Console.WriteLine("That world never came");
Console.WriteLine();
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("And they say");
Console.WriteLine();
Console.WriteLine("That a hero could save us");
Console.WriteLine();
Console.WriteLine("I'm not gonna stand here and wait");
Console.WriteLine();
Console.WriteLine("I'll hold on the wings of the eagles");
Console.WriteLine();
Console.WriteLine("Watch as we all fly away");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("Now that the world isn't ending");
Console.WriteLine();
Console.WriteLine("It's love that i'm sending to you");
Console.WriteLine();
Console.WriteLine("It isn't the love of a hero");
Console.WriteLine();
Console.WriteLine("And that's why I fear it won't do");
Console.WriteLine();
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("And they say");
Console.WriteLine();
Console.WriteLine("That a hero could save us");
Console.WriteLine();
Console.WriteLine("I'm not gonna stand here and wait");
Console.WriteLine();
Console.WriteLine("I'll hold on the wings of the eagles");
Console.WriteLine();
Console.WriteLine("Watch as we all fly away");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("And they're watching us");
Console.WriteLine();
Console.WriteLine("They're watching us");
Console.WriteLine();
Console.WriteLine("As we all fly away");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("And they're watching us");
Console.WriteLine();
Console.WriteLine("They're watching us");
Console.WriteLine();
Console.WriteLine("As we all fly away");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("And they're watching us");
Console.WriteLine();
Console.WriteLine("They're watching us");
Console.WriteLine();
Console.WriteLine("As we all fly away");
Console.WriteLine();